---
title: 'Effect of Povery/Minority/Age Group on ElderNet Utilziation'
output: github_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = T, fig.height = 7, fig.width = 9, message = FALSE, warning = FALSE)
options(scipen = 100)

library(tidyverse)
library(lubridate)
library(purrr)
library(skimr)
library(here)
library(tidyr)
library(stringr)
library(ggsci)
library(infer)
library(broom)
library(tidymodels)

```

```{r}

#load data
path <-
  list.files(path = here("data"), pattern = ".csv")

file_names <-
  c("care_mgmt", "client_info", "donations", "pantry", "volunteer")

path %>% 
  map( ~ read_csv(here("data", .))) %>% 
  set_names(file_names) %>%
  list2env(., envir = .GlobalEnv)


global_min <-
  min(
    c(
      min(as.Date(care_mgmt$assistance_date)),
      min(as.Date(mdy_hm(pantry$assistance_date))),
      min(as.Date(mdy(volunteer$appt_date)))
    )
  )

global_min

global_max <- 
  max(
    c(
      max(as.Date(care_mgmt$assistance_date)),
      max(as.Date(mdy_hm(pantry$assistance_date))),
      max(as.Date(mdy(volunteer$appt_date)))
    )
  )


global_min

global_max

```


```{r}

client_info_adj <- 
  client_info %>%
  select(anon_ID) %>%
  mutate(date = as.Date("2019-01-01")) %>%
  group_by(anon_ID) %>%
  padr::pad(group = "anon_ID", interval = "day", start_val = as.Date(global_min), end_val = as.Date(global_max))

# each client now has 1 entry per day
client_info_adj %>% 
  group_by(anon_ID) %>% 
  tally(name = "days")

client_info <- 
  client_info %>%
  inner_join(., client_info_adj, "anon_ID") %>%
  mutate(month = floor_date(date, 'month')) %>%
  select(-date) %>%
  ungroup() %>%
  distinct()

# rolled up into months - each client has 1 entry per 33 months
client_info %>% 
  group_by(anon_ID) %>% 
  tally(name = 'months')

```

```{r}

client <- 
  "210"

care_mgmt_util <-
  care_mgmt %>%
  # filter(anon_ID == client) %>%
  mutate(month = as.Date(floor_date(assistance_date, 'month'))) %>%
  group_by(anon_ID, month) %>%
  summarise(total_care_mgmt_encounters = n(),
            total_care_mgmt_mins = sum(amount, na.rm = T),
            mean_care_mgmt_mins = mean(amount, na.rm = T))

care_mgmt_util %>% 
  filter(anon_ID == client)

pantry_util <- 
  pantry %>%
  # filter(anon_ID == client) %>%
  mutate(month = as.Date(floor_date(mdy_hm(assistance_date), 'month'))) %>%
  group_by(anon_ID, month) %>%
  summarise(total_pantry_encounters = n(),
            total_pantry_pounds = sum(amount, na.rm = T),
            mean_pantry_pounds = mean(amount, na.rm = T))

pantry_util %>% 
  filter(anon_ID == client)

volunteer_util <- 
  volunteer %>%
  # filter(anon_ID == client) %>%
  mutate(month = as.Date(floor_date(mdy(appt_date), 'month'))) %>%
  group_by(anon_ID, month) %>%
  summarise(total_volunteer_encounters = n(),
            total_volunteer_mins = sum(appt_duration, na.rm = T),
            mean_volunteer_mins = mean(appt_duration, na.rm = T))

volunteer_util %>% 
  filter(anon_ID == client)


monthly_util <-
  client_info %>%
  left_join(., care_mgmt_util, by = c("anon_ID", "month")) %>%
  left_join(., pantry_util, by = c("anon_ID", "month")) %>% 
  left_join(., volunteer_util, by = c("anon_ID", "month")) %>% 
  ungroup() %>%
  as_tibble() %>% 
  rowwise() %>% 
  mutate(util = sum(mean_care_mgmt_mins, mean_pantry_pounds, mean_volunteer_mins, na.rm = T)) 

monthly_util %>% 
  filter(anon_ID == client)

```   


```{r}

monthly_util %>%
  group_by(month) %>%
  summarise(mean_util = mean(util, na.rm = T),
            sd_util = sd(util, na.rm = T)) %>%
  ggplot(aes(x = month, y = mean_util)) +
  geom_point() +
  geom_line() + 
  labs(x = "month", y = "Utiliziation Score", title = "Utilziation Score",
       subtitle = "Utilization score = monthly avg care mgmt mins + monthly avg pantry lbs + monthly avg volunteer mins")

```

```{r}

plot_data  <- 
  function(data, variable){
    
    data %>%
      select(month, one_of(variable), util) %>%
      rename(variable = 2) %>%
      group_by(month, variable) %>%
      summarise(mean_util = mean(util, na.rm = T),
                sd_util = sd(util, na.rm = T)) %>%
      ggplot(aes(x = month, y = mean_util, color = variable)) +
      geom_point() +
      geom_line() + 
      labs(x = "month", y = "Utiliziation Score", title = glue::glue("Utilziation Score by {variable}"),
           subtitle = "Utilization score = monthly avg care mgmt mins + monthly avg pantry lbs + monthly avg volunteer mins")
    
  }

plot_data(monthly_util, "minority")
plot_data(monthly_util, "poverty")
plot_data(monthly_util, "age_group")

```
