---
title: 'Exploring Utilziation Metric Idea'
output: github_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, fig.height = 7, fig.width = 9, message = FALSE, warning = FALSE)
options(scipen = 100)

library(tidyverse)
library(lubridate)
library(purrr)
library(skimr)
library(here)
library(tidyr)
library(stringr)
library(ggsci)

# some custom functions
round_numerics <- 
  function(data, digits = 2){
    data %>%
      mutate(across(where(is.numeric), ~ round(.x, digits)))
  }

add_table <- 
  function(data){
    data %>%
      round_numerics() %>%
      reactable::reactable(., fullWidth = F, resizable = T, filterable = T, 
                           highlight = T, defaultPageSize = 10, wrap = FALSE,
                           showSortIcon = T, striped = T, compact = T)
  }

bg_theme <- 
  function(base_size = 11,
           strip_text_size = 12,
           strip_text_margin = 10,
           subtitle_size = 13,
           subtitle_margin = 10,
           plot_title_size = 14,
           plot_title_margin = 10,
           font = "RobotoMono-Regular",
           ...) {
    
    ret <-
      ggplot2::theme_gray(base_family = font,
                          base_size = base_size, ...,) +
      theme(
        panel.background = element_rect(fill = "#e9e9ea"),
        plot.background = element_rect(fill = "#f3f3f3"),
        legend.background = element_rect(fill = "#f3f3f3"),
        panel.grid = element_line(color = "#ffffff"),
        panel.grid.major = element_line(color = "#ffffff")
        )
    
    ret$strip.text <-
      ggplot2::element_text(
        # hjust = 0,
        vjust = -.8,
        size = strip_text_size,
        margin = ggplot2::margin(b = strip_text_margin),
        family = font
      )
    
    ret$plot.subtitle <-
      ggplot2::element_text(
        hjust = 0,
        size = subtitle_size,
        margin = ggplot2::margin(b = subtitle_margin),
        family = font
      )
    
    ret$plot.title <-
      ggplot2::element_text(
        hjust = 0,
        size = plot_title_size,
        margin = ggplot2::margin(b = plot_title_margin),
        family = font
      )
    
    ret
  }

bg_red <- "#E64B35"
bg_green <- "#00a087"
bg_blue <- "#4DBBD5"

#load data
path <-
  list.files(path = here("data"), pattern = ".csv")

file_names <-
  c("care_mgmt", "client_info", "donations", "pantry", "volunteer")

path %>% 
  map( ~ read_csv(here("data", .))) %>% 
  set_names(file_names) %>%
  list2env(., envir = .GlobalEnv)
  
```

```{r}

client <- 
  "210"

care_mgmt_util <-
  care_mgmt %>%
  # filter(anon_ID == client) %>%
  mutate(month = as.Date(floor_date(assistance_date, 'month'))) %>%
  group_by(anon_ID, month) %>%
  summarise(total_care_mgmt_encounters = n(),
            total_care_mgmt_mins = sum(amount, na.rm = T),
            mean_care_mgmt_mins = mean(amount, na.rm = T))

pantry_util <- 
  pantry %>%
  # filter(anon_ID == client) %>%
  mutate(month = as.Date(floor_date(mdy_hm(assistance_date), 'month'))) %>%
  group_by(anon_ID, month) %>%
  summarise(total_pantry_encounters = n(),
            total_pantry_pounds = sum(amount, na.rm = T),
            mean_pantry_pounds = mean(amount, na.rm = T))

volunteer_util <- 
  volunteer %>%
  # filter(anon_ID == client) %>%
  mutate(month = as.Date(floor_date(mdy(appt_date), 'month'))) %>%
  group_by(anon_ID, month) %>%
  summarise(total_volunteer_encounters = n(),
            total_volunteer_mins = sum(appt_duration, na.rm = T),
            mean_volunteer_mins = mean(appt_duration, na.rm = T))

total_util <-
  client_info %>%
  # filter(anon_ID == client) %>%
  # select(anon_ID) %>%
  left_join(., care_mgmt_util, by = c("anon_ID")) %>%
  left_join(., pantry_util, by = c("anon_ID", "month")) %>%
  left_join(., volunteer_util, by = c("anon_ID", "month")) 

total_util %>% add_table()


total_util %>%
  group_by(month, poverty) %>%
  summarise(total_care_mgmt_encounters = sum(total_care_mgmt_encounters)) %>%
  ggplot(., aes(x = month, y = total_care_mgmt_encounters, group = poverty, fill = poverty, color = poverty)) + 
  geom_point()  +
  geom_line() + 
  scale_x_date(breaks = scales::date_breaks("3 months"))

total_util %>%
  group_by(month, poverty) %>%
  summarise(total_pantry_encounters = sum(total_pantry_encounters, na.rm = T)) %>%
  ggplot(., aes(x = month, y = total_pantry_encounters, group = poverty, fill = poverty, color = poverty)) + 
  geom_point()  +
  geom_line() + 
  scale_x_date(breaks = scales::date_breaks("3 months"))

total_util %>%
  group_by(month, poverty) %>%
  summarise(total_pantry_pounds = sum(total_pantry_pounds, na.rm = T)) %>%
  ggplot(., aes(x = month, y = total_pantry_pounds, group = poverty, fill = poverty, color = poverty)) + 
  geom_point()  +
  geom_line() + 
  scale_x_date(breaks = scales::date_breaks("3 months"))

```

monthly total ElderNet services for single client:
```{r}

total_util %>%
  select(month, starts_with("total")) %>%
  pivot_longer(2:ncol(.)) %>%
  padr::pad(group = "name") %>%
  padr::fill_by_value(value, 0) %>%
  ggplot(., aes(x = month, y = value, color = name)) + 
  geom_point() + 
  geom_line() + 
  facet_wrap(vars(name), scales = 'free') + 
  bg_theme(base_size = 10) + 
  scale_color_npg() + 
  theme(legend.position = 'none')

```

monthly average ElderNet services for single client:
```{r}

total_util %>%
  select(month, starts_with("mean")) %>%
  pivot_longer(2:ncol(.)) %>%
  padr::pad(group = "name") %>%
  padr::fill_by_value(value, 0) %>%
  ggplot(., aes(x = month, y = value, color = name)) + 
  geom_point() + 
  geom_line() + 
  facet_wrap(vars(name), scales = 'free') + 
  bg_theme(base_size = 10) + 
  scale_color_npg() + 
  theme(legend.position = 'none')

```