---
title: "Aging in Place"
subtitle: "DRAFT"
author: "An datathon organized by R-Ladies Philly & Data Philly"
date: "2/16/2022 - 4/15/2022"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background

The "Aging in Place" datathon aimed to connect and enable data science enthusiasts in the Philadelphia region to learn and collaborate, while exploring how programs for elderly and disabled individuals can serve the community now and in the future. Data analyses were completed by participants in groups, focusing on one of 3 main topics: 1) ElderNet's impact in the community, 2) an insights dashboard to support decision-making, and 3) growth opportunities and new ideas. 

## Partners

[ElderNet of Lower Merion and Narberth](https://eldernet.org/) is a nonprofit organization that was founded in 1976 by representatives of community, religious and governmental groups. ElderNet serves adults of all ages, especially frail older or younger disabled persons with low to moderate incomes who reside in Lower Merion or Narberth. ElderNet helps older neighbors remain independent and provides a variety of free, practical services so they have access to healthcare, food security, and an improved quality of life. ElderNet also provides information to individuals who need assistance with housing, nursing care, or other necessities. ElderNet served as the sponsor for this datathon, providing data and invaluable subject matter expertise.

[R-Ladies Philly](https://www.rladiesphilly.org/) is the Philadelphia chapter of R-Ladies Global, a world-wide organization that promotes gender diversity in the R community and in data science more broadly. Since its start in January 2018, R-Ladies Philly has brought together Philadelphia's data science community through informal monthly meetups that are skills-focused, free, and interdisciplinary; happy hour series; real-world data analytic projects helping local nonprofits; and collaborative engagements with other local tech data science groups. 

[DataPhilly](https://www.meetup.com/DataPhilly/) is a community run group for anyone interested in gaining insights from data. Topics include (but are not limited to) predictive analytics, applied machine learning, big data, data warehousing and data science. 


## Data 

Participants were given access to de-identified datasets covering ElderNet services between January 2019 and October 2021. These included basic de-identified demographics on clients (e.g. county, poverty status, minority group, and age label), information on clients' interactions with ElderNet's care management program (e.g. assistance date, communication type, benefits and assistance discussed per interaction), information on rides provided by ElderNet volunteers to clients (e.g. date of each ride taken and main reason for ride), and a history of clients' visits to ElderNet's food pantry (e.g. visit date, type of assistance, quantity of food). Additionally, participants were given access to information on donations received by ElderNet (e.g. donor zip code, amount and campaign). 

### Data De-Identification Process

Datathon organizers helped de-identify the datasets after signing confidentiality agreements. Unique clients from care management, volunteer services and food pantry were identified, and a comprehensive list was created. A new, random list of client IDs was created, and a crosswalk was generated between ElderNet's IDs and the new datathon IDs. Each dataset was re-coded to use the newly generated client IDs, and any identifiable data was removed. As part of the de-identification process, client race information was transformed to a minority flag (yes/no) and income information was reduced to a poverty flag (yes/no) using criteria not shared with datathon participants (but provided to ElderNet separately). ElderNet client's ages were transformed into age ranges, and random letters were assigned to these age ranges. These letters were the only age information provided to datathon participants (no translation to clients' real age range was provided to participants, but this was provided to ElderNet separately). Finally, clients' location information was reduced to county level (Montgomery or Other). 

### Preprocessing of Care Management data

The care management dataset was provided to datathon organizers as text entries. As part of data preprocessing, a set of categories of benefits and assistance types were defined, and each text line was hand coded into one of these categories. The category definitions are listed below: 

Assistance types:

-   **Coordination:** following up with client or service provider, connecting with other parties to facilitate something for the client
-   **Continuation:** helping client maintain their existing benefits
-   **Enrollment:** helping with the enrollment process
-   **Filing:** submitting forms (when enrollment/continuation of benefits unclear)
-   **Information:** providing information, explaining documents
-   **Referral:** referral to a provider, informing client of specific providers for their problem
-   **Support:** to do with in person visits, social visits, doing things for the participant, bringing things to the participant, buying things for the participant

Benefit types

-   **ADL:** activities of daily living (bathing, dressing, moving around in the house, going to the bathroom, etc); e.g. Home health Aides
-   **ElderNet:** to do with being an ElderNet participant; overall support/services provided by ElderNet
-   **Financial:** pension, SSDI, SS, retirement, debt, taxes, etc
-   **Food:** ability to access and obtain food
-   **Housing:** living situation (rent, mortgage, moving into assisted living, or nursing home); to do with a person's living environment, including repairs, cleaning up, etc
-   **Legal:** power of attorney, advance directives, ID & identity theft; voting
-   **Medical:** physical and mental health care, including health insurance, and rehab; includes Waiver program
-   **Pets:** Pet care, pet food
-   **Safety:** emergency preparedness, firearm removal, hoarding, etc
-   **Social:** social visit, questions about social activity, etc
-   **Telecommunication:** access and use of phone service, internet, TV; things to do with technology
-   **Transportation:** access to public transit, medical and nonmedical transportation, etc
-   **Utilities:** electric, gas, water

### Recommendations for data collection

- Individual interactions (particularly in Care Management) should be broken down into individual interactions to facilitate more accurae reporting. For example, if an ElderNet employee speaks with a colleague and then follows up with the client based on that conversation, make sure those are two records; we saw instances of notes where all these details were encompassed into the same note.
