---
title: "2022 Datathon (R Ladies Philly / Data Philly"
author: "Team 1"
date: "4/5/2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ElderNet's Impact in the Community

### Executive Summary

### Contributors

* Bulleted List
* 

### Problem Definition

[ElderNet of Lower Merion and Narberth](https://eldernetonline.org/) is a nonprofit organization that was founded in 1976 by representatives of community, religious and governmental groups. ElderNet serves adults of all ages, especially frail older or younger disabled persons with low to moderate incomes who reside in Lower Merion or Narberth. ElderNet helps older neighbors remain independent and provides a variety of free, practical services so they have access to healthcare, food security, and an improved quality of life. ElderNet also provides information to individuals who need assistance with housing, nursing care, or other necessities.

The role of Team 1 in this Datathon was to explore the impact of ElderNet services on the community it serves.

### Dataset

Data from ElderNet was deitentified and recoded by the Datathon leads and was provided to the teams as five distinct datasets. Clients were assigned unique identifier to allow comparison and merging across datasets.

* Care Management: A summary of the assistance received by each client and the associated benefit to that client
* Client Info: Basic demographics (County, poverty status, minority status, and a blinded age group assignment)
* Donations: A summary of ElderNet donation information; no client information
* Pantry: A summary of the food provided to each client via the Pantry service
* Volunteer Services: A summary of the rides provided to each client and the pusrpose of each ride

Some basic data cleaning was required for the Care Management dataset to correct for typos etc. A cleaned version of this dataset can be found [here]().

There were a large number of missing values in the assistance and benefit categories within the Care Management dataset. Further, these variables were split into three assistance and three benefit categories, to allow capture of multiple assistance events on a single date. To consolidate this information and minimize NA values, these variables were merged. The merged version of this dataset can be found [here]().

### Results

### Conclusions

### References

